### ISSUE TITLE
'Sym' object has no attribute 'lo'

### ISSUE THREAD

**Issue by apoorvacha** [apoorvacha/ASE_Project#1]
Coc1000 and  coc10000 and SSN.csv

For all other csv's 

'Sym' object has no attribute 'lo' 
for csv's. -> pom.csv, SSM.csv, healthCloseIsses12mths0011-easy.csv, healthCloseIsses12mths0001-hard.csv

**Comment by apoorvacha** [comment]
For all csv other than pom and china

**Comment by vasuagrawal19** [comment]
Blank spaces in the dataset were causing this issue. Now resolved.
